name: Use Custom Action

on: workflow_dispatch

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run dummy Action
        uses: ./.github/actions/my-first-action/
        with:
          name: "Partha"
